blog183/urls.py
from django.conf.urls import url, include
from django.conf import settings
from rest_framework import routers

from . import views

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'blogposts', views.BlogPostViewSet)
router.register(r'comments', views.CommentViewSet)

app_name = 'blog'
urlpatterns = [
    # url('^', include('django.contrib.auth.urls')),
    url(r'^login/$', views.login_view, name='login_view'),
    url(r'^logout/$', views.logout_view, name='logout_view'),
    # url(r'^$', views.index, name='index'),
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^page/(?P<page>[0-9]+)/$', views.PageIndexView.as_view(), name='page'),
    # url(r'^(?P<blogpost_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/comment/$', views.comment, name='comment'),
    # url(r'^(?P<pk>[0-9]+)/edit/$', views.edit, name='edit'),
    url(r'^(?P<pk>[0-9]+)/edit/$', views.EditView.as_view(), name='edit'),
    url(r'^(?P<pk>[0-9]+)/pdf/$', views.pdf, name='pdf'),
    # url(r'^(?P<blogpost_id>[0-9]+)/comment/$', views.comment, name='comment'),
    url(r'^newpost/$', views.newpost, name='newpost'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^about/$', views.about, name='about'),
    url(r'^archive/$', views.ArchiveIndexView.as_view(), name='archive'),
    #url(r'^archive/$', views.archive, name='archive'),
    url(r'^archive/(?P<year>[0-9]+)/(?P<month>[0-9]+)/$', views.ArchiveDetailView.as_view(),
         name='archive_detail'),
    # url(r'^archive/(?P<year>[0-9]+)/(?P<month>[0-9]+)/$', views.archive_detail,
    #      name='archive_detail'),
    url(r'^api/', include(router.urls), name='api'),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    # url(r'^apipi/list/$', views.blogpost_list, name='apipi_list'),
    # url(r'^apipi/(?P<pk>[0-9]+)/$', views.blogpost_detail, name='apipi_detail'),
]

firstsite183/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from firstsite183 import views

urlpatterns = [
	url(r'^$', views.home, name='home'),
	url(r'^polls/', include('polls183.urls', namespace="polls")),
	url(r'^blog/', include('blog183.urls', namespace="blog")),
	#url(r'^wiki/', include('wiki183.urls', namespace="wiki")),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # urlpatterns += patterns('',
    #     (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
    #     'document_root': settings.MEDIA_ROOT}))

blog183/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.encoding import python_2_unicode_compatible
from django.urls import reverse

@python_2_unicode_compatible  # only if you need to support Python 2
class BlogPost(models.Model):
    blogpost_title = models.CharField(max_length=200)
    blogpost_content = models.TextField(max_length=2000)
    pub_date = models.DateTimeField('date published')
    image = models.ImageField(blank=True, upload_to='blogimages')  # /%Y/%m/%d')
    likes = models.IntegerField(default=0)
    dislikes = models.IntegerField(default=0)
    author = models.ForeignKey(User, related_name='blogposts')
    # author = models.ForeignKey('UserProfile')

    def __str__(self):
        return self.blogpost_title

    def get_absolute_url(self):
        return reverse('blog:detail', args=[str(self.id)])

@python_2_unicode_compatible  # only if you need to support Python 2
class UserProfile(models.Model):
    user = models.OneToOneField(User)
    votes = models.IntegerField(default=0)
    occupation = models.CharField(max_length=50)
    city = models.CharField(max_length=30)
    province = models.CharField(max_length=50)
    sex = models.CharField(max_length=1)

    def __str__(self):
        return self.blogpost_title

@python_2_unicode_compatible  # only if you need to support Python 2
class Comment(models.Model):
    blogpost = models.ForeignKey(BlogPost, related_name='comments')
    # user = models.OneToOneField(User)
    user = models.ForeignKey(User, related_name='comments')
    comment_content = models.TextField(max_length=2000)
    votes = models.IntegerField(default=0)
    created = models.DateTimeField('created')

blog183/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User
from .models import BlogPost

class SignupForm0(forms.Form):
	username = forms.CharField(label="username", max_length=30)
	firstname = forms.CharField(label="firstname", max_length=30, required=False)
	lastname = forms.CharField(label="lastname", max_length=30, required=False)
	email = forms.EmailField()

class SignupForm(ModelForm):
	password1 = forms.CharField(label=("Password"), widget=forms.PasswordInput)
	password2 = forms.CharField(label=("Password confirmation"),
		widget=forms.PasswordInput,
		help_text=("Enter the same password as above, for verification."))

	def clean(self):
		cleaned_data = super(SignupForm, self).clean()
		pw1 = cleaned_data.get('password1')
		pw2 = cleaned_data.get('password2')

		if pw1 != pw2:
			raise forms.ValidationError("Passwords don't match")

	class Meta:
		model = User
		fields = ['username', 'first_name', 'last_name', 'email']


class EditForm(ModelForm):
	class Meta:
		model = BlogPost
		fields = ['blogpost_title', 'blogpost_content', 'image']       

blog183/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.utils import timezone
from django.core.urlresolvers import reverse
from django.views import generic
from django.contrib.auth import views, authenticate, login, logout
from django.views.decorators.csrf import csrf_exempt

from .models import BlogPost, Comment, UserProfile
from .forms import SignupForm, EditForm

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import Group, User
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail, BadHeaderError

from rest_framework.renderers import JSONRenderer
from rest_framework.parsers import JSONParser
from rest_framework.response import Response
from rest_framework.decorators import api_view, detail_route, list_route
from rest_framework import viewsets
from .serializers import UserSerializer, BlogPostSerializer, CommentSerializer

from reportlab.pdfgen import canvas

import re

USER_RE = re.compile(r"^[a-zA-Z0-9_-]{3,20}$")
PASSWORD_RE = re.compile(r"^.{3,20}$")
EMAIL_RE = re.compile(r"^[\S]+@[\S]+\.[\S]+$")

def signup(request):
    if request.method == 'POST':
        # form = UserCreationForm(request.POST)
        form = SignupForm(request.POST)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.set_password(request.POST["password1"])
            new_user.save()
            # g = Group.objects.get(name='BlogUser')
            # g.user_set.add(new_user)
            # user = authenticate(username=username, password=password)
            new_user = authenticate(username=request.POST['username'], 
                password=request.POST['password1'])
            login(request, new_user)
            return HttpResponseRedirect(reverse('blog:index'))
        else:
            return render(request, "blog/signup.html", {'form': form, })
    if request.method == 'GET':
        # form = UserCreationForm()
        form = SignupForm()
        return render(request, "blog/signup.html", {'form': form, })

class IndexView(generic.ListView):
    template_name = 'blog/index.html'
    context_object_name = 'post_list'
    queryset = BlogPost.objects.order_by('-pub_date')[:5]
    
    # def get_queryset(self):
	# 	return BlogPost.objects.order_by('-pub_date')[:5]
	# latest_post_list = BlogPost.objects.order_by('-pub_date')[:5]
	# context = {'latest_post_list': latest_post_list}
	# return render(request, 'blog/index.html', context)

class PageIndexView(generic.ListView):
    template_name = 'blog/index.html'
    context_object_name = 'post_list'
    queryset = BlogPost.objects.all().order_by('-pub_date')
    paginate_by = 5

    # def get_queryset(self):
    #     item = 5 * (int(self.kwargs['page']) - 1)
    #     return BlogPost.objects.all().order_by('-pub_date')
        # return BlogPost.objects.order_by('-pub_date')[item:item+5]

class DetailView(generic.DetailView):
    model = BlogPost
    template_name = 'blog/detail.html'

    def get_context_data(self, *args, **kwargs):
        context = super(DetailView, self).get_context_data(*args, **kwargs)
        bp = super(DetailView, self).get_object()
        comments = Comment.objects.filter(blogpost_id=bp.id)
        comments = comments.order_by('-created')[:5]
        context['comments_list'] = comments
        return context

# def detail(request, blogpost_id):
#     post = get_object_or_404(BlogPost, pk=blogpost_id)
#     return render(request, 'blog/detail.html', {'post': post})

@login_required(login_url='blog:login_view')
def comment(request, pk):
    if request.method == 'GET':
        bp = get_object_or_404(BlogPost, pk=pk)
        return render(request, 'blog/comment.html', {'blogpost': bp})
    if request.method == 'POST':
        try:
            co = request.POST['comment']
            bp = get_object_or_404(BlogPost, pk=pk)
            user = request.user
            comment = Comment(blogpost=bp, user=user, comment_content=co,
                created=timezone.now())
        except (KeyError, Comment.DoesNotExist):
            # Redisplay the new comment form.
            return render(request, 'blog/pk/comment.html', {
                'error_message': "Error :(",
            })
        else:
            comment.save()
            return HttpResponseRedirect(reverse('blog:detail', args=(pk,)))

# def comment(request, blogpost_id):
#    return HttpResponse("You're commenting on post %s." % blogpost_id)

@login_required(login_url='blog:login_view')
def newpost(request):
    if request.method == 'GET':
	    return render(request, 'blog/newpost.html')
    if request.method == 'POST':
        try:
            subject = request.POST['subject']
            content = request.POST['content']
            author = request.user
            image = request.FILES.get('image', None)
            #mage = request.FILES['image']
            # image = None
            bp = BlogPost(blogpost_title=subject, blogpost_content=content, 
                author= author, image=image, pub_date=timezone.now())
        except (KeyError, BlogPost.DoesNotExist):
            # Redisplay the new post form.
            return render(request, 'blog/newpost.html', {
                'error_message': "Error :( " + str(KeyError) +
                 str(request.FILES.keys()),
            })
        else:
            if len(subject)!=0 and len(content)!=0: 
                bp.save()
                # Always return an HttpResponseRedirect after successfully dealing
                # with POST data. This prevents data from being posted twice if a
                # user hits the Back button.
                # return HttpResponseRedirect('/blog/%s' % str(bp.id))
                return HttpResponseRedirect(reverse('blog:detail', args=(bp.id,)))
            else:
                return render(request, 'blog/newpost.html', {
                'error_message': "The post must have title and content", })


@login_required(login_url='blog:login_view')
def edit(request, pk):
    bp = get_object_or_404(BlogPost, pk=pk)
    if request.method == 'GET':
        form = EditForm(request.POST, instance=bp)
        return render(request, "blog/edit.html", {'bp': bp, 'form': form, })
    if request.method == 'POST':
        form = EditForm(request.POST, instance=bp)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('blog:detail', args=(bp.id,)))
        # try:
        #     subject = request.POST['subject']
        #     content = request.POST['content']
        #     author = request.user
        #     image = request.FILES['image']
        #     bp = BlogPost(blogpost_title=subject, blogpost_content=content, 
        #         author= author, image=image, pub_date=timezone.now())
        # except (KeyError, BlogPost.DoesNotExist):
        #     # Redisplay the edit post form.
        #     bp = get_object_or_404(BlogPost, pk=pk)
        #     return render(request, 'blog/edit.html', {'bp': bp, 
        #         'error_message': "Error :(" + str(KeyError) +
        #          str(request.FILES.keys()),
        #     })
        else:
            bp.save()
            return HttpResponseRedirect(reverse('blog:detail', args=(bp.id,)))

class EditView(generic.edit.UpdateView):
    model = BlogPost
    fields = ['blogpost_title', 'blogpost_content', 'image']
    template_name = 'blog/edit.html'

def pdf(request, pk):
    bp = get_object_or_404(BlogPost, pk=pk)
    filename = str(pk) + '.pdf'
    # Create the HttpResponse object with the appropriate PDF headers.
    response = HttpResponse(content_type='application/pdf')
    # Open pdf in browser
    # response['Content-Disposition'] = 'filename=' + filename
    # Save file pop-up
    response['Content-Disposition'] = 'attachment; filename=' + filename
    # response['Content-Disposition'] = 'attachment; filename="somefilename.pdf"'

    # Create the PDF object, using the response object as its "file."
    p = canvas.Canvas(response)

    # Draw things on the PDF. Here's where the PDF generation happens.
    # See the ReportLab documentation for the full list of functionality.
    p.drawString(100, 750, "First Site Blog")
    p.drawString(100, 700, bp.blogpost_title)
    p.drawString(100, 670, bp.blogpost_content)
    if bp.image:
        p.drawImage(bp.image.path, 100, 550, width=100, height=100, mask=None)
    p.drawString(100, 500, "By " + str(bp.author) + ", " + str(bp.pub_date))

    # Close the PDF object cleanly, and we're done.
    p.showPage()
    p.save()
    return response

def contact(request):
    if request.method == 'GET':
        return render(request, 'blog/contact.html')
    if request.method == 'POST':
        subject = request.POST.get('subject', '')
        message = request.POST.get('message', '')
        from_email = request.POST.get('from_email', '')

        if subject and message and from_email:
            try:
                send_mail(subject, message, from_email, ['angelmm_hup@yahoo.es'])
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return HttpResponseRedirect(reverse('blog:index'))
        else:
            # In reality we'd use a form class
            # to get proper validation errors.
            return HttpResponse('Make sure all fields are entered and valid.')

# def archive(request):
#     return render(request, 'blog/archive.html')

class ArchiveIndexView(generic.ListView):
    template_name = 'blog/archive.html'
    context_object_name = 'month_list'
    pubdates = [(p.pub_date.year, p.pub_date.month, p.pub_date.strftime("%B")) 
                for p in BlogPost.objects.all()]
    #queryset = list(set(pubdates))
    queryset = sorted(set(pubdates))

def archive_detail(request, year, month):
    return HttpResponse("Year %s, month %s posts." % (year, month))

class ArchiveDetailView(generic.ListView):

blog183/templates/blog/about.html
{% extends "base.html" %}

{% block content %}

<h2>About this blog</h2>

<div>
	<p>This is not just a blog.</p>
</div>

{% endblock %}

blog183/templates/blog/archive.html
{% extends "base.html" %}

{% block content %}

<h2>Archived posts by month</h2>

{% if month_list %}
    {% for month in month_list %}
        <a href="{% url 'blog:archive_detail' year=month.0 month=month.1 %}">{{ month.2 }} {{ month.0 }}</a>
        <br>
    {% endfor %}
    
{% else %}
    <p>No archived months are available.</p>
{% endif %}

{% if is_paginated %}
    <div class="pagination">
        <span class="page-links">
            {% if page_obj.has_previous %}
                <a href="/blog/page/{{ page_obj.previous_page_number }}">previous</a>
            {% endif %}
            <span class="page-current">
                page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
            </span>
            {% if page_obj.has_next %}
                <a href="/blog/page/{{ page_obj.next_page_number }}">next</a>
            {% endif %}
        </span>
    </div>
{% endif %}

{% endblock %}

blog183/templates/blog/archive_detail.html
{% extends "base.html" %}

{% block content %}

<h2>Archived posts by month</h2>

{% if post_list %}
    <div class="postlist">
    {% for post in post_list %}
        <div class="archive-post">
            <div class="col-8">
                <a class="archive-post-title" href="{% url 'blog:detail' post.id %}">{{ post.blogpost_title }}</a>
                <div class="post-tag">
                    Posted by {{ post.author }} on {{ post.pub_date|date:"d M Y, H:i" }} 
                </div>
            </div>
        </div>

    {% endfor %}
    </div>
    
{% else %}
    <p>No posts are available.</p>
{% endif %}

{% if is_paginated %}
    <div class="pagination">
        <span class="page-links">
            {% if page_obj.has_previous %}
                <a href="{% url 'blog:page' page_obj.previous_page_number %}">previous</a>
            {% endif %}
            <span class="page-current">
                page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
            </span>
            {% if page_obj.has_next %}
                <a href="{% url 'blog:page' page_obj.next_page_number %}">next</a>
            {% endif %}
        </span>
    </div>
{% else %}
	<div class="pagination">
        <span class="page-links">
            {% if post_list.count > 0 %}
                <a href="{% url 'blog:page' 2 %}">next</a>
            {% endif %}
        </span>
    </div>
{% endif %}

{% endblock %}

blog183/templates/blog/comment.html
{% extends "base.html" %}

{% block content %}

	<h2>{{user.username}}'s comment on {{ blogpost.blogpost_title }}</h2>

	{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

	<form method="post">
	{% csrf_token %}

	<form enctype="multipart/form-data" method="post">

		<label>
			<div>comment</div>
			<textarea name="comment">{{comment}}</textarea>
		</label>
		<label>
			<div>image</div>
	  		<input type="file" name="image">
	  	</label>
		<div class="error">{{error_message}}</div>

		<input type="submit" value="Send Comment">
	</form>

{% endblock %}

blog183/templates/blog/contact.html
{% extends "base.html" %}

{% block content %}

<h2>Contact us</h2>

{% if error_message %}
	<p><strong>{{ error_message }}</strong></p>
{% endif %}

<form method="post">
	{% csrf_token %}
    <label>
        <div>name</div>
        <input type="text" name="name" value="{{name}}">
    </label>
    <label>
        <div>email</div>
        <input type="text" name="from_email" value="{{from_email}}">
    </label>
    <label>
        <div>link</div>
        <input type="text" name="link" value="{{link}}">
    </label>
    <label>
        <div>subject</div>
        <input type="text" name="subject" value="{{subject}}">
    </label>
    <label>
        <div>message</div>
        <textarea name="message">{{content}}</textarea>
    </label>
    <div class="error">{{error}}</div>

    <input type="submit" value="Send">
</form>

{% endblock %}

blog183/templates/blog/detail.html
{% extends "base.html" %}

{% block content %}

<div class="detail-post">
	<div class="post-title">{{ blogpost.blogpost_title }}</div>
	<div class="post-content">{{ blogpost.blogpost_content }}</div>
	{% if blogpost.image %}
		<a href="{{blogpost.image.url}}">
			<img src="{{blogpost.image.url}}" max-height="300px">
		</a>
	{% endif %}
	<div class="post-tag">
		Posted by {{ blogpost.author }} on {{ blogpost.pub_date|date:"d-m-Y, H:i" }}
	</div>
	<div class="post-likes">Likes: {{ blogpost.likes }}</div>

	<div class="actions">
		<a class="pdf-link" href="{% url 'blog:pdf' blogpost.id %}">PDF</a>
		<a class="edit-link" href="{% url 'blog:edit' blogpost.id %}">Edit</a>
		<a class="comment-link" href="{% url 'blog:comment' blogpost.id %}">Comment</a>
	</div>
	<hr>
	<div class="comments">
		{{ comments_list.count}} comment{{comments_list.count|pluralize }}
		{% for co in comments_list %}
			<div class="comment-content">{{co.comment_content}}</div>
			<div class="comment-tag">By {{co.user}} ({{co.created}})</div>
			<hr>
		{% endfor %}
	</div>
</div>

{% endblock %}

blog183/templates/blog/edit.html
{% extends "base.html" %}

{% block content %}

<h2>Going to edit {{bp.blogpost_title}}</h2>

{% if error_message %}
	<p><strong>{{ error_message }}</strong></p>
{% endif %}

<form enctype="multipart/form-data" method="post">
	{% csrf_token %}
    {{ form.as_p }}
    {% if bp.image %}
		<img src="{{bp.image.url}}" width="225px" height="150px">
	{% endif %}
    <input type="submit" value="send edited post">
</form>

{% endblock %}

blog183/templates/blog/edit0.html
{% extends "base.html" %}

{% block content %}

<h2>Going to edit {{bp.blogpost_title}}</h2>

{% if error_message %}
	<p><strong>{{ error_message }}</strong></p>
{% endif %}

<form enctype="multipart/form-data" method="post">
	{% csrf_token %}
	
	<label>
		<div>edit subject</div>
		<input type="text" name="subject" value="{{bp.blogpost_title}}">
	</label>

	<label>
		<div>edit content</div>
		<textarea name="content">{{bp.blogpost_content}}</textarea>
	</label>
	<label>
		{% if bp.image %}
			<img src="{{bp.image.url}}" width="225px" height="150px">
		{% endif %}
		<div>change image</div>
  		<input type="file" name="image">
  	</label>
	<div class="error">{{error_message}}</div>

	<input type="submit" value="send edited post">
</form>

{% endblock %}

blog183/templates/blog/index.html
{% extends "base.html" %}

{% block content %}

{% if post_list %}
    <div class="postlist">
    {% for post in post_list %}
        <div class="post">
            <div class="col-4">
                {% if post.image %}
                    <img src="{{post.image.url}}" width="225px" height="150px">
                {% else %}
                    <img src="http://placehold.it/225x150">
                {% endif %}
            </div>
            <div class="col-8">
                <a class="post-title" href="{% url 'blog:detail' post.id %}">{{ post.blogpost_title }}</a>
                <div class="post-content">
                    {{ post.blogpost_content|truncatewords:60 }}
                </div>

                <div class="post-tag">
                    Posted by {{ post.author }} on {{ post.pub_date|date:"d M Y, H:i" }} 
                </div>
            </div>
        </div>

    {% endfor %}
    </div>
    
{% else %}
    <p>No posts are available.</p>
{% endif %}

{% if is_paginated %}
    <div class="pagination">
        <span class="page-links">
            {% if page_obj.has_previous %}
                <a href="{% url 'blog:page' page_obj.previous_page_number %}">previous</a>
            {% endif %}
            <span class="page-current">
                page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
            </span>
            {% if page_obj.has_next %}
                <a href="{% url 'blog:page' page_obj.next_page_number %}">next</a>
            {% endif %}
        </span>
    </div>
{% else %}
	<div class="pagination">
        <span class="page-links">
            {% if post_list.count > 0 %}
                <a href="{% url 'blog:page' 2 %}">next</a>
            {% endif %}
        </span>
    </div>
{% endif %}

{% endblock %}

blog183/templates/blog/login-view.html
{% extends "base.html" %}

{% block content %}

<h2>Blog Login</h2>

<form method="post" action="{% url 'blog:login_view' %}">
	{% csrf_token %}
	<table>
		<tr>
		    <td>User:</td>
			<td><input type="text" name="username" value="{{username}}"></td>
		</tr>
		<tr>
		    <td>Password:</td>
			<td><input type="password" name="password" ></td>
		</tr>
		<tr>
			{{ error }}
		</tr>
	</table>

	<input type="submit" value="login" />
	<input type="hidden" name="next" value="{{ next }}" />

</form>

{% endblock %}

blog183/templates/blog/newpost.html
{% extends "base.html" %}

{% block content %}

<h2>Going to create a new post</h2>

{% if error_message %}
	<p><strong>{{ error_message }}</strong></p>
{% endif %}

<form enctype="multipart/form-data" method="post">
	{% csrf_token %}
	
	<label>
		<div>subject</div>
		<input type="text" name="subject" value="{{subject}}">
	</label>

	<label>
		<div>content</div>
		<textarea name="content">{{content}}</textarea>
	</label>
	<label>
		<div>image</div>
  		<input type="file" name="image">
  	</label>
	<div class="error">{{error_message}}</div>

	<input type="submit" value="Send Post">
</form>

{% endblock %}

blog183/templates/blog/signup.html
{% extends "base.html" %}

{% block content %}

<h2>Blog Signup</h2>

  <form action="" method="post">
  	{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Sign Up">
  </form>

{% endblock %}