blog183/urls.py
from django.conf.urls import url, include
from django.conf import settings
from rest_framework import routers

from . import views

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'blogposts', views.BlogPostViewSet)
router.register(r'comments', views.CommentViewSet)

app_name = 'blog'
urlpatterns = [
    # url('^', include('django.contrib.auth.urls')),
    url(r'^login/$', views.login_view, name='login_view'),
    url(r'^logout/$', views.logout_view, name='logout_view'),
    # url(r'^$', views.index, name='index'),
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^page/(?P<page>[0-9]+)/$', views.PageIndexView.as_view(), name='page'),
    # url(r'^(?P<blogpost_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/comment/$', views.comment, name='comment'),
    # url(r'^(?P<pk>[0-9]+)/edit/$', views.edit, name='edit'),
    url(r'^(?P<pk>[0-9]+)/edit/$', views.EditView.as_view(), name='edit'),
    url(r'^(?P<pk>[0-9]+)/pdf/$', views.pdf, name='pdf'),
    # url(r'^(?P<blogpost_id>[0-9]+)/comment/$', views.comment, name='comment'),
    url(r'^newpost/$', views.newpost, name='newpost'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^about/$', views.about, name='about'),
    url(r'^archive/$', views.ArchiveIndexView.as_view(), name='archive'),
    #url(r'^archive/$', views.archive, name='archive'),
    url(r'^archive/(?P<year>[0-9]+)/(?P<month>[0-9]+)/$', views.ArchiveDetailView.as_view(),
         name='archive_detail'),
    # url(r'^archive/(?P<year>[0-9]+)/(?P<month>[0-9]+)/$', views.archive_detail,
    #      name='archive_detail'),
    url(r'^api/', include(router.urls), name='api'),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    # url(r'^apipi/list/$', views.blogpost_list, name='apipi_list'),
    # url(r'^apipi/(?P<pk>[0-9]+)/$', views.blogpost_detail, name='apipi_detail'),
]

firstsite183/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from firstsite183 import views

urlpatterns = [
	url(r'^$', views.home, name='home'),
	url(r'^polls/', include('polls183.urls', namespace="polls")),
	url(r'^blog/', include('blog183.urls', namespace="blog")),
	#url(r'^wiki/', include('wiki183.urls', namespace="wiki")),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # urlpatterns += patterns('',
    #     (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
    #     'document_root': settings.MEDIA_ROOT}))

templates/firstsite/index - copia.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}"> {{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

templates/firstsite/index-bootstrap.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Django Project</title>
  <link href='https://fonts.googleapis.com/css?family=Lato:300,100' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="{% static '/css/bootstrap.css' %}">
  <link rel="stylesheet" href="{% static '/css/styles.css' %}">
  <script type="text/javascript" src="{% static 'js/jquery-1.11.3.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
</head>
  <body>
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <img class="title-logo" src="{% static 'images/logo.png' %}" alt="Udacity logo">
        </div>
        <div class="col-md-6 text-right text-uppercase">
          <h1 class="title-super text-thin">Django Project</h1>
          <h4>By Angel MM</h4>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <hr>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <img src="http://placekitten.com/1140/400" class="img-responsive" alt="Main kitten image">
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <h2 class="text-muted">Featured Work</h2>
        </div>
      </div>
      <div class="row text-center">
        <div class="col-md-4">
          <img src="http://placekitten.com/480/400" class="img-responsive" alt="Appify Kitten" data-toggle="modal" data-target="#project1">
          <h3 class="text-uppercase">Blog</h3>
          <p><a href="/blog/">Link to project</a></p>
        </div>
        <div class="col-md-4">
          <img src="http://placekitten.com/480/400" class="img-responsive" alt="Sunflower Kitten" data-toggle="modal" data-target=".im-modal-sm">
          <h3 class="text-uppercase">Polls</h3>
          <p><a href="/polls/">Link to project</a></p>
        </div>
        <div class="col-md-4">
          <img src="http://placekitten.com/480/400" class="img-responsive" alt="Bokeh Kitten" data-toggle="modal" data-target="#project3">
          <h3 class="text-uppercase">Wiki</h3>
          <p><a href="/wiki/">Link to project</a></p>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <hr>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <h2>Bootstrap JS</h2>
        </div>
      </div>
      <div class="row">
        <div class="col-md-3">
          <h4>Dropdown</h4>
            <!-- Dropdown button -->
            <div class="dropdown">
              <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Dropdown
                <span class="caret"></span>
              </button>
              <ul class="dropdown-menu" role="menu">
                  <li><a href="#">Coffee</a></li>
                  <li><a href="#">Tea</a></li>
                  <li><a href="#">Milk</a></li>
                  <li class="divider"></li>
                  <li class="disabled"><a href="#">Orange</a></li>
              </ul>
            </div>
          </div>
          <div class="col--md-3">
            <h4>ScrollSpy</h4>
            
          </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <hr>
        </div>
      </div>
      <div class="row text-center">
        <div class="col-md-6">
          <h5>About</h5>
        </div>
        <div class="col-md-6">
          <h5>Contact</h5>
        </div>
      </div> 
    </div>

    <!-- Modal 1 -->
    <div class="modal fade" id="project1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title" id="myModalLabel">Appify</h4>
          </div>
          <div class="modal-body">
            <img class="img-responsive" src="http://placekitten.com/480/400" alt="appify_image">
            <p>
              This was my first project in this class. I learned a lot about HTML, CSS and Bootstrap.
            </p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>

    <!-- Modal 2 Small -->
    <div class="modal fade im-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-sm">
        <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title" id="myModalLabel">Sunflower</h4>
          </div>
          <div class="modal-body">
            <img class="img-responsive" src="http://placekitten.com/480/400" alt="sunflower_image">
            <p>
              This was my second project in this class. I don't know why this page is full of kittens. Aren't they adorable?
            </p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>

    <!-- Modal 3 No fade -->
    <div class="modal" id="project3" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title" id="myModalLabel">Bokeh</h4>
          </div>
          <div class="modal-body">
            <img class="img-responsive" src="http://placekitten.com/480/400"  alt="bokeh_image">
            <p>
              This was my third project in this class. What does "Bokeh" mean? Just another absurd app name, I guess.
            </p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>

</body>
</html>

templates/firstsite/index.html
<h1>Hello, First site with Django 1.8</h1>
<a href="/blog/">blog</a><br>
<a href="/polls/">polls</a><br>
<a href="/wiki/">wiki</a><br>